# Generated by Django 3.2.3 on 2021-05-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=100)),
                ('img', models.CharField(default='unknown', max_length=100)),
                ('url', models.CharField(default='unknown', max_length=100)),
                ('price_min', models.CharField(default='unknown', max_length=100)),
                ('price_max', models.CharField(default='unknown', max_length=100)),
                ('socket', models.CharField(default='unknown', max_length=100)),
                ('line', models.CharField(default='unknown', max_length=100)),
                ('generation', models.CharField(default='unknown', max_length=100)),
            ],
        ),
    ]
